/*
 * generated by Xtext 2.11.0
 */
package com.github.parisoft.noop.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class NOOPWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public NOOPWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
