/*
 * generated by Xtext 2.10.0
 */
package org.parisoft.noop.ui.wizard


import com.google.inject.Inject
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.resource.FileExtensionProvider

class NoopNewProjectWizardInitialContents {
	@Inject
	FileExtensionProvider fileExtensionProvider

	def generateInitialContents(IFileSystemAccess2 fsa) {
		fsa.generateFile(
			"src/Hello." + fileExtensionProvider.primaryFileExtension,
			'''
			Hello {
				
			}
			'''
			)
	}
}
