/*
 * generated by Xtext 2.11.0
 */
package com.github.parisoft.noop

import com.google.inject.Binder
import com.google.inject.name.Names
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy
import org.eclipse.xtext.scoping.IScopeProvider
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider
import com.github.parisoft.noop.scoping.NOOPImportedNamespaceAwareLocalScopeProvider
import com.github.parisoft.noop.scoping.NOOPResourceDescriptionsStrategy

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NOOPRuntimeModule extends AbstractNOOPRuntimeModule {

	override void configureIScopeProviderDelegate(Binder binder) {
		binder.bind(IScopeProvider).annotatedWith(Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(
			NOOPImportedNamespaceAwareLocalScopeProvider)
	}

	def Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return NOOPResourceDescriptionsStrategy;
	}
}
