/*
 * generated by Xtext 2.11.0
 */
package com.github.parisoft.noop


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NOOPStandaloneSetup extends NOOPStandaloneSetupGenerated {

	def static void doSetup() {
		new NOOPStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
