/*
 * generated by Xtext 2.10.0
 */
package org.parisoft.noop


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NoopRuntimeModule extends AbstractNoopRuntimeModule {
}
