/*
 * generated by Xtext 2.10.0
 */
package org.parisoft.noop


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NoopStandaloneSetup extends NoopStandaloneSetupGenerated {

	def static void doSetup() {
		new NoopStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
