/*
 * generated by Xtext 2.11.0
 */
package com.github.parisoft.noop.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class NOOPOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
